// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, feed_name, feed_url, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, feed_name, feed_url, user_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedName  string
	FeedUrl   string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedName,
		arg.FeedUrl,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedName,
		&i.FeedUrl,
		&i.UserID,
	)
	return i, err
}

const userWhoCreatedFeed = `-- name: UserWhoCreatedFeed :many
SELECT feed_name, feed_url, user_name
FROM feeds
JOIN users
ON feeds.user_id = users.id
`

type UserWhoCreatedFeedRow struct {
	FeedName string
	FeedUrl  string
	UserName string
}

func (q *Queries) UserWhoCreatedFeed(ctx context.Context) ([]UserWhoCreatedFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, userWhoCreatedFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWhoCreatedFeedRow
	for rows.Next() {
		var i UserWhoCreatedFeedRow
		if err := rows.Scan(&i.FeedName, &i.FeedUrl, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
